version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node20-api
    env_file: .env
    ports:
      - "3001:3001"
      - "3002:3002"
    restart: unless-stopped
    command: sh -c "npm run db:seed:js && npm start"
